name: CI (pytest)

on:
  pull_request:
    paths:
      - "core/**"
      - "controllers/**"
      - "adapters/**"
      - "tests/**"
      - "requirements.txt"
  push:
    branches: [ main, master ]
    paths:
      - "core/**"
      - "controllers/**"
      - "adapters/**"
      - "tests/**"
      - "requirements.txt"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q